# Generated by Django 2.2.4 on 2019-08-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('soldMonth', models.IntegerField()),
                ('soldYear', models.IntegerField()),
                ('soldDaily', models.IntegerField()),
                ('soldWeekly', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
