# Generated by Django 2.2.4 on 2019-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerNum', models.IntegerField()),
                ('customerfName', models.CharField(max_length=25)),
                ('customerlName', models.CharField(max_length=25)),
                ('finalSale', models.FloatField()),
                ('discount', models.FloatField()),
                ('sendInvoice', models.CharField(max_length=200)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='costPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='salesPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
