# Generated by Django 2.2.3 on 2019-08-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190810_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
