# Generated by Django 2.2.3 on 2019-08-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_invoiceitem_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item')),
            ],
        ),
    ]
