# Generated by Django 2.2.3 on 2019-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_stockupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='totalStock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
