# Generated by Django 2.2.3 on 2019-08-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190811_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='soldDaily',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='soldMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='soldWeekly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='soldYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
